version: '2'
services:
    airtraffic-app:
        image: airtraffic
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://airtraffic-postgresql:5432/AirTraffic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    airtraffic-postgresql:
        extends:
            file: postgresql.yml
            service: airtraffic-postgresql
